name: CI-CD

on:
  push:
    branches: ["main"]

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Build auth-service
        run: mvn -B clean test package
        working-directory: backend-microservices/auth-service

      - name: Build order-service
        run: mvn -B clean test package
        working-directory: backend-microservices/order-service

      - name: Build inventory-service
        run: mvn -B clean test package
        working-directory: backend-microservices/inventory-service

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push auth-service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/auth-service:latest backend-microservices/auth-service
          docker push ${{ secrets.DOCKER_USERNAME }}/auth-service:latest

      - name: Build and push order-service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/order-service:latest backend-microservices/order-service
          docker push ${{ secrets.DOCKER_USERNAME }}/order-service:latest

      - name: Build and push inventory-service
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/inventory-service:latest backend-microservices/inventory-service
          docker push ${{ secrets.DOCKER_USERNAME }}/inventory-service:latest
